// apps/accessible-blocks/src/App.tsx
import { MorphicBlocks, type MorphicCodeEditorTheme } from "morphic-blocks";
import { useEffect, useRef, useState } from "preact/hooks";
import { behaviors } from "./behaviors";
import definitions from "./definitions.json";
import javaCss from "./modes/java.css";
import symbolsCss from "./modes/symbols.css";
import wordsCss from "./modes/words.css";
import program from "./program.json";
import { SIZE_MAX, SIZE_MIN, loadSettings, saveSettings, type Level, type Settings } from "./settings";

// Symbols, Words and Java are modes: they change what a block says. Each
// has a twin with "-help" that also shows the explanation on its tile, and
// definitions.json has a preset for every pair.
const levels: { id: Level; label: string; mode: string; preview: string }[] = [
  { id: "symbols", label: "Symbols", mode: "with-symbols", preview: "plain words" },
  { id: "words", label: "Words", mode: "in-words", preview: "Java" },
  { id: "java", label: "Java", mode: "in-java", preview: "plain words" },
];
const levelOf = (id: Level) => levels.find((level) => level.id === id)!;
const presetName = (settings: Settings) => (settings.help ? `${settings.level}-help` : settings.level);

const modeStyles = {
  "with-symbols": symbolsCss,
  "with-symbols-help": symbolsCss,
  "in-words": wordsCss,
  "in-words-help": wordsCss,
  "in-java": javaCss,
  "in-java-help": javaCss,
};

// The text size changes how things look, not what they say: Blockly's zoom
// for the workspace, CSS for everything else.
const scaleOf = (settings: Settings) => settings.size / 100;

// Code view colors per look; the page's own colors live in style.css.
const codeColors = {
  light: { background: "#fffdf8", foreground: "#111111", gutterBackground: "#f6f1e7", gutterForeground: "#6b6358", selectionBackground: "#efe3ff" },
  dark: { background: "#1d1928", foreground: "#ece7f5", gutterBackground: "#1d1928", gutterForeground: "#a197b5", selectionBackground: "#3d2e5c" },
  lightContrast: { background: "#ffffff", foreground: "#000000", gutterBackground: "#ffffff", gutterForeground: "#000000", selectionBackground: "#ffe066" },
  darkContrast: { background: "#000000", foreground: "#ffffff", gutterBackground: "#000000", gutterForeground: "#ffffff", selectionBackground: "#665200" },
};

function codeTheme(settings: Settings): MorphicCodeEditorTheme {
  const look = settings.dark ? (settings.contrast ? "darkContrast" : "dark") : settings.contrast ? "lightContrast" : "light";
  return {
    ...codeColors[look],
    fontFamily: settings.dyslexia ? '"OpenDyslexic", monospace' : 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
    fontSize: `${Math.round(15 * scaleOf(settings))}px`,
    lineHeight: 1.6,
  };
}

/** Wait for the dyslexia font, so blocks are measured with it, not before. */
const dyslexiaFontReady = () =>
  Promise.all([document.fonts.load('400 16px "OpenDyslexic"'), document.fonts.load('700 16px "OpenDyslexic"')]);

export function App() {
  const [settings, setSettings] = useState(loadSettings);
  const [output, setOutput] = useState<{ lines: string[]; error?: string }>({ lines: [] });
  const [settingsOpen, setSettingsOpen] = useState(false);
  const engine = useRef<MorphicBlocks>();
  // The settings the engine shows right now, to tell what changed.
  const applied = useRef<Settings>();
  const toolboxEl = useRef<HTMLDivElement>(null);
  const workspaceEl = useRef<HTMLDivElement>(null);
  const previewEl = useRef<HTMLDivElement>(null);
  const settingsButton = useRef<HTMLButtonElement>(null);
  const closeButton = useRef<HTMLButtonElement>(null);

  const change = (patch: Partial<Settings>) => setSettings((current) => ({ ...current, ...patch }));

  const run = () => {
    const result = engine.current?.runJavaScript();
    if (!result) return;
    setOutput({ lines: result.output.map((line) => line.text), error: result.error?.message });
  };

  useEffect(() => {
    const created = new MorphicBlocks(definitions, behaviors);
    engine.current = created;
    const mounted = created.mount({
      workspaceContainer: workspaceEl.current!,
      previewContainer: previewEl.current!,
      preset: presetName(settings),
      modeStyles,
      previewTheme: codeTheme(settings),
      // The toolbox is mounted below, so Blockly builds none itself.
      canvasToolbox: true,
      blockly: {
        // Served by the app itself (scripts/copy-blockly-media.mjs), so
        // Blockly never loads images or sounds from Google's server.
        media: "blockly-media/",
        // Zelos has large, rounded blocks that are easy to hit.
        renderer: "zelos",
        trashcan: true,
        zoom: { controls: true, wheel: false, startScale: scaleOf(settings) },
        theme: {
          name: "accessible-blocks",
          base: "classic",
          // The page's CSS paints the workspace, so each look can change it.
          componentStyles: { workspaceBackgroundColour: "transparent", scrollbarColour: "#8a7fa3" },
        },
      },
    });
    // The toolbox is mounted on its own because only this call can leave out
    // the "Mode:" label; mount() always shows it.
    created.mountToolbox(toolboxEl.current!, { modeLabel: false });
    created.loadWorkspace(program);
    created.getWorkspace()?.scroll(0, 0);
    // Show what the starting program prints once everything is set up, so
    // the output matches the blocks on screen.
    void mounted.then(run);
    return () => created.dispose();
  }, []);

  // Every change of level or look goes through here, so the page, the modes
  // and Blockly always agree.
  useEffect(() => {
    saveSettings(settings);
    const root = document.documentElement;
    root.style.fontSize = `${settings.size}%`;
    root.style.setProperty("--tile-zoom", String(scaleOf(settings)));
    root.dataset.bsTheme = settings.dark ? "dark" : "light";
    root.classList.toggle("dark", settings.dark);
    root.classList.toggle("high-contrast", settings.contrast);
    root.classList.toggle("dyslexia", settings.dyslexia);

    let cancelled = false;
    void (async () => {
      if (settings.dyslexia) await dyslexiaFontReady();
      const current = engine.current;
      if (cancelled || !current) return;
      const before = applied.current;
      applied.current = settings;
      // Each level comes as a preset with and without explanations in the
      // toolbox, so one call switches every view.
      const preset = presetName(settings);
      if (current.getActivePreset()?.name !== preset) current.applyPreset(preset);
      // Setting the workspace mode again measures its blocks again, so a new
      // block font takes effect (also on load, when the font was saved as on
      // and arrived after the first measuring).
      if (before ? before.dyslexia !== settings.dyslexia : settings.dyslexia) {
        current.setModes({ workspaceMode: levelOf(settings.level).mode });
      }
      current.getWorkspace()?.setScale(scaleOf(settings));
      current.setPreviewTheme(codeTheme(settings));
    })();
    return () => {
      cancelled = true;
    };
  }, [settings]);

  // The settings panel is a dialog: Escape closes it, and focus moves into it
  // and back to its button.
  useEffect(() => {
    if (!settingsOpen) return;
    closeButton.current?.focus();
    const onKey = (event: KeyboardEvent) => event.key === "Escape" && setSettingsOpen(false);
    addEventListener("keydown", onKey);
    return () => {
      removeEventListener("keydown", onKey);
      settingsButton.current?.focus();
    };
  }, [settingsOpen]);

  const level = levelOf(settings.level);

  return (
    <>
      <a class="skip-link" href="#workspace">
        Skip to your program
      </a>
      <div class="shell" inert={settingsOpen}>
        <header class="app-bar">
          <div class="brand">
            <img src="logo.svg" alt="" width="36" height="36" />
            <h1>Accessible Blocks</h1>
          </div>
          <div class="btn-group level-switch" role="radiogroup" aria-label="Show blocks as">
            {levels.map((option) => (
              <>
                <input
                  type="radio"
                  class="btn-check"
                  name="level"
                  id={`level-${option.id}`}
                  checked={settings.level === option.id}
                  onChange={() => change({ level: option.id })}
                />
                <label class="btn btn-level" for={`level-${option.id}`}>
                  {option.label}
                </label>
              </>
            ))}
          </div>
          <button
            ref={settingsButton}
            type="button"
            class="btn btn-settings"
            aria-expanded={settingsOpen}
            aria-controls="settings"
            onClick={() => setSettingsOpen(true)}>
            Settings
          </button>
        </header>

        <main class="app-grid">
          <section class="pane toolbox-pane" aria-labelledby="toolbox-title">
            <h2 id="toolbox-title">Blocks</h2>
            <p class="pane-hint">Drag a block into your program.</p>
            <div ref={toolboxEl} class="toolbox" />
          </section>

          <section class="pane workspace-pane" aria-labelledby="workspace-title">
            <h2 id="workspace-title">Your program</h2>
            <div ref={workspaceEl} id="workspace" class="workspace" tabIndex={-1} />
          </section>

          <aside class="side">
            <section class="pane" aria-labelledby="preview-title">
              <h2 id="preview-title">The same program in {level.preview}</h2>
              <div ref={previewEl} class="preview" />
            </section>
            <section class="pane" aria-labelledby="output-title">
              <div class="output-head">
                <h2 id="output-title">Output</h2>
                <button type="button" class="btn btn-run" onClick={run}>
                  Run
                </button>
              </div>
              <pre class="output" aria-live="polite">
                {output.lines.join("\n")}
                {output.error && <span class="output-error">{`\n${output.error}`}</span>}
                {output.lines.length === 0 && !output.error && "The program showed nothing."}
              </pre>
            </section>
          </aside>
        </main>
      </div>

      <div
        id="settings"
        class={`offcanvas offcanvas-end settings${settingsOpen ? " show" : ""}`}
        role="dialog"
        aria-modal="true"
        aria-labelledby="settings-title"
        tabIndex={-1}>
        <div class="offcanvas-header">
          <h2 id="settings-title" class="offcanvas-title">
            Settings
          </h2>
          <button
            ref={closeButton}
            type="button"
            class="btn-close"
            aria-label="Close settings"
            onClick={() => setSettingsOpen(false)}
          />
        </div>
        <div class="offcanvas-body">
          <p class="settings-intro">
            Symbols, Words and Java change what the blocks say. These settings change how everything looks.
          </p>

          <div class="mb-4">
            <label class="form-label size-label" for="setting-size">
              Text size <output for="setting-size">{settings.size}%</output>
            </label>
            <input
              type="range"
              class="form-range"
              id="setting-size"
              min={SIZE_MIN}
              max={SIZE_MAX}
              step={10}
              value={settings.size}
              aria-valuetext={`${settings.size} percent`}
              onInput={(event) => change({ size: Number(event.currentTarget.value) })}
            />
          </div>

          {(
            [
              ["dark", "Dark theme", "Light text on a dark background."],
              ["contrast", "High contrast", "The strongest difference between text and background, with outlined blocks."],
              ["dyslexia", "Font for dyslexia", "OpenDyslexic, with heavier letter bottoms."],
              ["help", "Explain each block", "A short explanation under every block in the toolbox."],
            ] as const
          ).map(([key, label, hint]) => (
            <div class="form-check form-switch setting">
              <input
                class="form-check-input"
                type="checkbox"
                role="switch"
                id={`setting-${key}`}
                aria-describedby={`setting-${key}-hint`}
                checked={settings[key]}
                onChange={(event) => change({ [key]: event.currentTarget.checked })}
              />
              <label class="form-check-label" for={`setting-${key}`}>
                {label}
              </label>
              <div id={`setting-${key}-hint`} class="form-text">
                {hint}
              </div>
            </div>
          ))}

          <p class="settings-note">
            The block colors are chosen so that people with color blindness can tell them apart, and every
            block also says what it does in words, so nothing depends on color alone.
          </p>
        </div>
      </div>
      {settingsOpen && <div class="offcanvas-backdrop fade show" onClick={() => setSettingsOpen(false)} />}
    </>
  );
}

// apps/turtle-drawing/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { MorphicBlocks } from "morphic-blocks";
  import definitions from "./definitions.json";
  import { behaviors } from "./behaviors";
  import program from "./program.json";
  import { recordProgram, type Pose, type Step } from "./turtle";
  import { penColor } from "./pens";
  import { StayInView } from "./stay-in-view";

  const START: Pose = { x: 0, y: 0, heading: 0, color: "ink" };
  const LINE_WIDTH = 5;

  let toolboxEl: HTMLDivElement;
  let workspaceEl: HTMLDivElement;
  let previewEl: HTMLDivElement;
  let spotEl: HTMLDivElement;
  let canvas: HTMLCanvasElement;
  let engine: MorphicBlocks;

  // Positions are relative to "home", the middle of the free paper area, so
  // the drawing moves along when the window changes size. `view` is how far
  // the paper was dragged and how much it was zoomed.
  let home = $state({ x: 0, y: 0 });
  let view = $state({ x: 0, y: 0, scale: 1 });
  let pose = $state<Pose>({ ...START });
  let running = $state(false);
  let message = $state("");
  let codeOpen = $state(false);

  type Line = { from: Pose; to: Pose };
  let lines: Line[] = [];
  let partial: Line | null = null;
  let frame = 0;

  function draw() {
    const ratio = window.devicePixelRatio || 1;
    const ctx = canvas.getContext("2d")!;
    ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.translate(home.x + view.x, home.y + view.y);
    ctx.scale(view.scale, view.scale);
    ctx.lineWidth = LINE_WIDTH;
    ctx.lineCap = "round";
    for (const line of partial ? [...lines, partial] : lines) {
      ctx.strokeStyle = penColor(line.to.color);
      ctx.beginPath();
      ctx.moveTo(line.from.x, line.from.y);
      ctx.lineTo(line.to.x, line.to.y);
      ctx.stroke();
    }
  }

  // Zoom around a point on the screen, so what is under it stays put.
  function zoomAt(x: number, y: number, factor: number) {
    const scale = Math.min(4, Math.max(0.25, view.scale * factor));
    const wx = (x - home.x - view.x) / view.scale;
    const wy = (y - home.y - view.y) / view.scale;
    view = { x: x - home.x - wx * scale, y: y - home.y - wy * scale, scale };
    draw();
  }

  // One finger or the mouse drags the paper; two fingers also pinch to zoom.
  const pointers = new Map<number, { x: number; y: number }>();

  function onPointerDown(event: PointerEvent) {
    canvas.setPointerCapture(event.pointerId);
    pointers.set(event.pointerId, { x: event.clientX, y: event.clientY });
  }

  function onPointerMove(event: PointerEvent) {
    if (!pointers.has(event.pointerId)) return;
    const before = [...pointers.values()];
    pointers.set(event.pointerId, { x: event.clientX, y: event.clientY });
    const after = [...pointers.values()];
    const mid = (points: { x: number; y: number }[]) => ({
      x: (points[0].x + points[1].x) / 2,
      y: (points[0].y + points[1].y) / 2,
    });
    if (after.length === 1) {
      view = { ...view, x: view.x + after[0].x - before[0].x, y: view.y + after[0].y - before[0].y };
      draw();
    } else if (after.length === 2) {
      const [a, b] = [mid(before), mid(after)];
      const spread = (p: { x: number; y: number }[]) => Math.hypot(p[0].x - p[1].x, p[0].y - p[1].y) || 1;
      view = { ...view, x: view.x + b.x - a.x, y: view.y + b.y - a.y };
      zoomAt(b.x, b.y, spread(after) / spread(before));
    }
  }

  function onPointerUp(event: PointerEvent) {
    pointers.delete(event.pointerId);
  }

  function layout() {
    const ratio = window.devicePixelRatio || 1;
    canvas.width = Math.round(window.innerWidth * ratio);
    canvas.height = Math.round(window.innerHeight * ratio);
    const rect = spotEl.getBoundingClientRect();
    home = { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 };
    draw();
  }

  // How long a step takes to play. Long programs play faster, so even a
  // big drawing is done within about ten seconds.
  function durations(steps: Step[]) {
    const base = steps.map((step) => {
      if (step.kind === "move") return Math.hypot(step.to.x - step.from.x, step.to.y - step.from.y) / 0.3;
      if (step.kind === "turn") return Math.abs(step.to.heading - step.from.heading) / 0.6;
      return 150;
    });
    const total = base.reduce((sum, ms) => sum + ms, 0);
    const speedUp = Math.max(1, total / 10000);
    return base.map((ms) => ms / speedUp);
  }

  function run() {
    if (running) return;
    message = "";
    const { steps, error } = recordProgram(engine.generateJavaScript(), pose);
    if (error) message = error.message;
    play(steps);
  }

  function play(steps: Step[]) {
    const times = durations(steps);
    let index = 0;
    let started = performance.now();
    running = true;

    const tick = (now: number) => {
      while (index < steps.length) {
        const step = steps[index];
        const t = Math.min(1, (now - started) / (times[index] || 1));
        if (step.kind === "color") {
          pose = step.to;
        } else {
          const at: Pose = {
            x: step.from.x + (step.to.x - step.from.x) * t,
            y: step.from.y + (step.to.y - step.from.y) * t,
            heading: step.from.heading + (step.to.heading - step.from.heading) * t,
            color: step.to.color,
          };
          pose = at;
          partial = step.kind === "move" ? { from: step.from, to: at } : null;
        }
        if (t < 1) break;
        if (step.kind === "move") lines.push({ from: step.from, to: step.to });
        partial = null;
        started += times[index];
        index++;
      }
      draw();
      if (index < steps.length) frame = requestAnimationFrame(tick);
      else running = false;
    };
    frame = requestAnimationFrame(tick);
  }

  function clear() {
    cancelAnimationFrame(frame);
    running = false;
    message = "";
    lines = [];
    partial = null;
    pose = { ...START };
    view = { x: 0, y: 0, scale: 1 };
    draw();
  }

  onMount(() => {
    engine = new MorphicBlocks(definitions, behaviors);
    void engine.mount({
      workspaceContainer: workspaceEl,
      // The program in Logo, shown read only in the </> popup.
      previewContainer: previewEl,
      previewTheme: {
        background: "#fffdf8",
        foreground: "#3b2f2a",
        gutterBackground: "#fbf3e4",
        gutterForeground: "#b9a88f",
        selectionBackground: "#f6e3c2",
        fontFamily: 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
        fontSize: "15px",
        lineHeight: 1.6,
      },
      // The toolbox is mounted below without its "Mode" label: this app
      // shows no words at all.
      canvasToolbox: true,
      modesFolder: import.meta.glob("./modes/*.css", { eager: true, query: "?inline" }),
      blockly: {
        // Blockly's images and sounds are served by the app itself
        // (scripts/copy-blockly-media.mjs), never by Google.
        media: "blockly-media/",
        renderer: "zelos",
        trashcan: true,
        zoom: { controls: true, startScale: 0.9 },
        move: { scrollbars: true, drag: true, wheel: true },
        // Keeps the view from wandering far away from the program.
        plugins: { metricsManager: StayInView },
        theme: {
          name: "turtle-drawing",
          base: "classic",
          componentStyles: {
            workspaceBackgroundColour: "#fffdf8",
            scrollbarColour: "#e3cfb2",
            scrollbarOpacity: 0.8,
          },
        },
      },
    });
    engine.mountToolbox(toolboxEl, { modeLabel: false });
    engine.loadWorkspace(program);
    engine.getWorkspace()?.scroll(0, 0);

    const onWheel = (event: WheelEvent) => {
      event.preventDefault();
      zoomAt(event.clientX, event.clientY, Math.exp(-event.deltaY * 0.0015));
    };
    canvas.addEventListener("wheel", onWheel, { passive: false });
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") codeOpen = false;
    };
    window.addEventListener("keydown", onKey);

    layout();
    const observer = new ResizeObserver(layout);
    observer.observe(spotEl);
    return () => {
      observer.disconnect();
      canvas.removeEventListener("wheel", onWheel);
      window.removeEventListener("keydown", onKey);
      cancelAnimationFrame(frame);
      engine.dispose();
    };
  });
</script>

<!-- The paper: a patterned background and the canvas the turtle draws on,
     which can be dragged and zoomed. -->
<div class="paper fixed inset-0"></div>
<canvas
  bind:this={canvas}
  class="fixed inset-0 h-full w-full cursor-grab touch-none active:cursor-grabbing"
  aria-label="Drawing"
  onpointerdown={onPointerDown}
  onpointermove={onPointerMove}
  onpointerup={onPointerUp}
  onpointercancel={onPointerUp}
></canvas>

<!-- The turtle, with a ring in the current pen color. -->
<div
  class="pointer-events-none fixed top-0 left-0 z-10 size-14"
  style="transform: translate({home.x + view.x + pose.x * view.scale - 28}px, {home.y + view.y + pose.y * view.scale - 28}px) scale({view.scale}) rotate({pose.heading}deg);"
>
  <div class="absolute inset-1 rounded-full opacity-30" style="background: {penColor(pose.color)};"></div>
  <img src="icons/turtle.svg" alt="" class="relative size-14" />
</div>

<div class="fixed inset-0 z-20 flex flex-col gap-3 p-3 pointer-events-none md:flex-row md:gap-4 md:p-5">
  <!-- The free paper area. The turtle's home is in its middle. -->
  <div class="relative min-h-0 flex-1 md:order-3">
    <!-- On phones the home spot stays clear of the buttons above it. -->
    <div bind:this={spotEl} class="absolute inset-x-0 top-20 bottom-0 md:top-0"></div>
    <div class="pointer-events-auto absolute top-0 right-0 flex gap-3">
      <button
        type="button"
        onclick={clear}
        aria-label="Clear"
        class="grid size-16 place-items-center rounded-full bg-wipe text-white shadow-[inset_0_-5px_0_var(--wipe-dark),0_6px_14px_var(--shadow)] transition active:translate-y-0.5 md:size-20"
      >
        <svg viewBox="0 0 32 32" class="size-8 md:size-10" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6l8 8-11 11H9l-4-4z" /><path d="M12 12l8 8" /><path d="M15 25h12" /></svg>
      </button>
      <button
        type="button"
        onclick={run}
        disabled={running}
        aria-label="Run"
        class="grid size-16 place-items-center rounded-full bg-go text-white shadow-[inset_0_-5px_0_var(--go-dark),0_6px_14px_var(--shadow)] transition active:translate-y-0.5 disabled:opacity-60 md:size-20"
      >
        <svg viewBox="0 0 32 32" class="ml-1 size-8 md:size-10" fill="currentColor"><path d="M9 5.5v21a1.5 1.5 0 0 0 2.3 1.3l16-10.5a1.5 1.5 0 0 0 0-2.6l-16-10.5A1.5 1.5 0 0 0 9 5.5z" /></svg>
      </button>
    </div>
    <!-- Zoom buttons in the bottom right corner. -->
    <div class="pointer-events-auto absolute right-0 bottom-0 flex flex-col gap-2">
      <button type="button" aria-label="Zoom in" onclick={() => zoomAt(home.x, home.y, 1.25)} class="small-button">
        <svg viewBox="0 0 24 24" class="size-5" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M12 5v14M5 12h14" /></svg>
      </button>
      <button type="button" aria-label="Zoom out" onclick={() => zoomAt(home.x, home.y, 0.8)} class="small-button">
        <svg viewBox="0 0 24 24" class="size-5" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M5 12h14" /></svg>
      </button>
    </div>
    {#if message}
      <div
        role="alert"
        class="pointer-events-auto absolute top-20 left-1/2 md:top-auto md:bottom-0 flex w-max max-w-full -translate-x-1/2 items-center gap-3 rounded-3xl bg-card px-4 py-3 font-bold shadow-lg ring-4 ring-wipe text-ink"
      >
        <img src="icons/turtle.svg" alt="" class="size-10 rotate-90" />
        <span>{message}</span>
      </div>
    {/if}
  </div>

  <!-- The toolbox column: one big tile per block, dragged onto the
       workspace, and at the bottom of the page the </> button for parents
       and teachers. -->
  <div class="pointer-events-none relative flex shrink-0 items-start gap-3 md:order-1 md:flex-col md:self-stretch">
    <div
      bind:this={toolboxEl}
      class="toolbox pointer-events-auto flex min-w-0 flex-1 justify-center gap-2.5 overflow-auto rounded-[28px] bg-card p-3 shadow-[0_10px_30px_var(--shadow)] md:flex-none md:flex-col md:justify-start"
      aria-label="Blocks"
    ></div>
    <!-- For parents and teachers: the program in Logo, a read only
         Morphic Blocks preview view. -->
    <div
      role="dialog"
      aria-label="The program in Logo"
      hidden={!codeOpen}
      class="pointer-events-auto absolute top-full right-0 z-30 mt-3 w-[min(22rem,calc(100vw-1.5rem))] rounded-2xl bg-card shadow-[0_10px_30px_var(--shadow)] ring-1 ring-black/10 md:top-auto md:right-auto md:bottom-0 md:left-full md:mt-0 md:ml-4"
    >
      <button type="button" aria-label="Close" onclick={() => (codeOpen = false)} class="absolute top-2 right-2 z-10 grid size-9 place-items-center rounded-full border-2 border-ink/70 bg-card text-ink/70 hover:text-ink hover:border-ink">
        <svg viewBox="0 0 24 24" class="size-4" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path d="M6 6l12 12M18 6L6 18" /></svg>
      </button>
      <div bind:this={previewEl} class="max-h-[min(16rem,30vh)] overflow-auto rounded-2xl py-2 pr-11"></div>
    </div>
    <div class="pointer-events-auto self-center md:mt-auto md:self-start">
      <button
        type="button"
        aria-label="Show the program in Logo"
        aria-expanded={codeOpen}
        onclick={() => (codeOpen = !codeOpen)}
        class="grid size-12 shrink-0 place-items-center rounded-full border-2 border-ink/70 bg-card font-mono text-sm font-bold text-ink/70 shadow-[0_6px_14px_var(--shadow)] hover:border-ink hover:text-ink"
      >
        &lt;/&gt;
      </button>
    </div>
  </div>

  <!-- The workspace, where the program is built. -->
  <div
    class="pointer-events-auto relative h-[42vh] shrink-0 overflow-hidden rounded-[28px] border-4 border-card bg-card shadow-[0_10px_30px_var(--shadow)] md:order-2 md:h-auto md:w-[380px]"
  >
    <div bind:this={workspaceEl} class="h-full w-full"></div>
  </div>
</div>
