// apps/level-up/src/App.tsx
import { For, Show, createSignal, onCleanup, onMount } from "solid-js";
import { MorphicBlocks } from "morphic-blocks";
import definitions from "./definitions.json";
import { logoSvg, theme } from "./theme";
import { behaviors } from "./behaviors";
import program from "./program.json";
import { modesFolder } from "./modes";

// Level n offers the blocks of the first n categories, so every level keeps
// everything before it.
const levels = [
  { topic: "Output", category: "Output" },
  { topic: "Variables and math", category: "Variables" },
  { topic: "Decisions", category: "Decisions" },
  { topic: "Loops", category: "Loops" },
  { topic: "Functions", category: "Functions" },
];
// The favicon is the logo as a data URI, so it costs no request.
document
  .querySelector<HTMLLinkElement>('link[rel="icon"]')
  ?.setAttribute("href", `data:image/svg+xml,${encodeURIComponent(logoSvg(theme.ink, theme.accent))}`);

const colorOf = (category: string) => definitions.categories.find((c) => c.name === category)?.color;
const blocksUpTo = (level: number) => {
  const open = new Set(levels.slice(0, level).map((l) => l.category));
  return definitions.blocks.filter((b) => open.has(b.category)).map((b) => b.identifier);
};

// Asking once per browser session is enough; after a refresh the question is
// back, so a new learner at the same computer still sees it.
const SKIP_KEY = "level-up:skip-remove-dialog";
const readSkip = () => {
  try {
    return sessionStorage.getItem(SKIP_KEY) === "1";
  } catch {
    return false;
  }
};
const saveSkip = () => {
  try {
    sessionStorage.setItem(SKIP_KEY, "1");
  } catch {
    // Storage may be blocked; the dialog then simply keeps asking.
  }
};

// Blockly registers morphic blocks under "morphic:<id>".
const cleanId = (type: string) => type.replace(/^morphic:/, "");

// JavaScript's wording for mistakes it finds itself, in Python's words.
const pythonError = (error: Error) => {
  const message = error.message;
  if (error instanceof SyntaxError && /break/.test(message)) return "SyntaxError: 'break' outside loop";
  if (error instanceof RangeError) return "RecursionError: maximum recursion depth exceeded";
  return /^\w+Error:/.test(message) ? message : `Error: ${message}`;
};

// Blockly's block type, reached through the engine (Blockly is not a
// direct dependency of the app).
type Workspace = NonNullable<ReturnType<MorphicBlocks["getWorkspace"]>>;
type Block = ReturnType<Workspace["getAllBlocks"]>[number];
const insideDef = (block: Block | null): boolean =>
  !!block && (cleanId(block.type) === "def" || insideDef(block.getSurroundParent()));

type Removal = { level: number; count: number; apply: () => void };

export function App() {
  let toolboxEl!: HTMLDivElement;
  let workspaceEl!: HTMLDivElement;
  let dialogEl!: HTMLDialogElement;
  let outputEl!: HTMLPreElement;
  let engine: MorphicBlocks | undefined;

  const [level, setLevel] = createSignal(1);
  const [lines, setLines] = createSignal<string[]>([]);
  const [error, setError] = createSignal<string | null>(null);
  const [pending, setPending] = createSignal<Removal | null>(null);
  const [dontAsk, setDontAsk] = createSignal(false);

  const run = () => {
    if (!engine) return;
    // The program runs as the body of a JavaScript function, where a stray
    // return is allowed. Python refuses to start such a program, so do that.
    const stray = engine
      .getWorkspace()
      ?.getAllBlocks(false)
      .some((b) => cleanId(b.type) === "return" && !insideDef(b));
    if (stray) {
      setLines([]);
      setError("SyntaxError: 'return' outside function");
      return;
    }
    const result = engine.runJavaScript();
    setLines(result.output.map((line) => line.text));
    setError(result.error ? pythonError(result.error) : null);
    // Keep the end in view: that is where an error shows up.
    queueMicrotask(() => (outputEl.scrollTop = outputEl.scrollHeight));
  };

  // mount() always shows every block, so the toolbox is set up on its own
  // with the level's subset, and set up again whenever the level changes.
  const showToolbox = (n: number) => {
    engine?.mountToolbox(toolboxEl, { blocks: blocksUpTo(n), modeLabel: false });
    const newest = levels[n - 1].category.toLowerCase();
    toolboxEl.dataset.newest = newest;
    // Bring the level's new blocks into view; the older ones sit above.
    const group = toolboxEl.querySelector<HTMLElement>(`[data-category="${newest}"]`);
    toolboxEl.scrollTop = group ? group.offsetTop : 0;
  };

  // Which blocks a lower level would take away: every block it does not
  // have, together with what sits inside it. Default values (shadows) do not
  // count; they belong to the block around them.
  const planRemoval = (n: number): Removal => {
    const workspace = engine!.getWorkspace()!;
    const allowed = new Set(blocksUpTo(n));
    const goes = (block: Block | null): boolean =>
      !!block && (!allowed.has(cleanId(block.type)) || goes(block.getSurroundParent()));
    const doomed = workspace.getAllBlocks(false).filter((b) => !b.isShadow() && goes(b));
    const outermost = doomed.filter((b) => !allowed.has(cleanId(b.type)) && !goes(b.getSurroundParent()));
    return {
      level: n,
      count: doomed.length,
      // A statement leaves a gap that the blocks below close; a value simply
      // leaves its slot (its default value comes back, if it has one).
      apply: () => outermost.forEach((b) => b.dispose(!!b.previousConnection)),
    };
  };

  const goTo = (n: number) => {
    if (n === level()) return;
    if (n < level()) {
      const removal = planRemoval(n);
      if (removal.count > 0 && !readSkip()) {
        setDontAsk(false);
        setPending(removal);
        dialogEl.showModal();
        return;
      }
      removal.apply();
    }
    setLevel(n);
    showToolbox(n);
  };

  const closeDialog = (confirmed: boolean) => {
    const removal = pending();
    dialogEl.close();
    setPending(null);
    if (!confirmed || !removal) return;
    if (dontAsk()) saveSkip();
    removal.apply();
    setLevel(removal.level);
    showToolbox(removal.level);
  };

  onMount(() => {
    engine = new MorphicBlocks(definitions, behaviors);
    void engine.mount({
      workspaceContainer: workspaceEl,
      // The toolbox is set up by showToolbox, so Blockly builds none itself.
      canvasToolbox: true,
      modesFolder,
      blockly: {
        // Served by the app itself (scripts/copy-blockly-media.mjs), so
        // Blockly never loads images or sounds from Google's server.
        media: "blockly-media/",
        renderer: "thrasos",
        trashcan: true,
        zoom: { controls: true, wheel: true, startScale: 1 },
        grid: { spacing: 28, length: 1, colour: theme.grid, snap: true },
        theme: {
          name: "level-up",
          base: "classic",
          componentStyles: {
            workspaceBackgroundColour: theme.workspace,
            scrollbarColour: theme.scrollbar,
            scrollbarOpacity: 0.7,
          },
        },
      },
    });
    showToolbox(level());
    engine.loadWorkspace(program);
    engine.getWorkspace()?.scroll(0, 0);
    // Show what the starting program prints; Run refreshes it later.
    run();
  });

  onCleanup(() => engine?.dispose());

  return (
    <div class="shell">
      <header class="top">
        <div class="brand">
          {/* The same logo as the favicon, colored by the page's CSS variables. */}
          <div class="logo" innerHTML={logoSvg("var(--ink)", "var(--accent)")} />
          <div class="brand-text">
            <span class="brand-name">Level Up</span>
            <span class="brand-sub">Python, one step at a time</span>
          </div>
        </div>
        <nav class="stairs" aria-label="Levels">
          <For each={levels}>
            {(item, i) => {
              const n = i() + 1;
              return (
                <button
                  type="button"
                  class="step"
                  classList={{ reached: n <= level(), current: n === level() }}
                  style={{ "--step-color": colorOf(item.category), "--rise": String(n) }}
                  aria-pressed={n === level()}
                  onClick={() => goTo(n)}
                >
                  <span class="step-number">Level {n}</span>
                  <span class="step-topic">{item.topic}</span>
                  <span class="step-bar" aria-hidden="true" />
                </button>
              );
            }}
          </For>
        </nav>
      </header>

      <main class="panes">
        <section class="pane toolbox" aria-label="Toolbox">
          <h2 class="pane-title">
            Blocks at level {level()}
          </h2>
          <div ref={toolboxEl} class="toolbox-body" />
        </section>

        <section class="pane workspace" aria-label="Your program">
          <h2 class="pane-title">Your program</h2>
          <div ref={workspaceEl} class="workspace-body" />
        </section>

        <section class="pane output" aria-label="Output">
          <div class="output-head">
            <h2 class="pane-title">Output</h2>
            <button type="button" class="run" onClick={run}>
              Run
            </button>
          </div>
          <pre ref={outputEl} class="output-body" aria-live="polite">
            {lines().join("\n")}
            <Show when={error()}>
              <span class="output-error">{`${lines().length ? "\n" : ""}${error()}`}</span>
            </Show>
            <Show when={!lines().length && !error()}>
              <span class="output-quiet">The program printed nothing.</span>
            </Show>
          </pre>
        </section>
      </main>

      <dialog
        ref={dialogEl}
        class="confirm"
        aria-labelledby="confirm-text"
        // Escape counts as Cancel.
        onCancel={(e) => {
          e.preventDefault();
          closeDialog(false);
        }}
      >
        <p id="confirm-text">
          Level {pending()?.level} removes {pending()?.count} {pending()?.count === 1 ? "block" : "blocks"} it does not
          have yet.
        </p>
        <label class="confirm-check">
          <input type="checkbox" checked={dontAsk()} onChange={(e) => setDontAsk(e.currentTarget.checked)} />
          Don't show this again
        </label>
        <div class="confirm-actions">
          <button type="button" class="quiet-button" onClick={() => closeDialog(false)}>
            Cancel
          </button>
          <button type="button" class="run" onClick={() => closeDialog(true)}>
            Continue
          </button>
        </div>
      </dialog>
    </div>
  );
}

// apps/accessible-blocks/src/App.tsx
import { MorphicBlocks, type MorphicCodeEditorTheme } from "morphic-blocks";
import { useEffect, useRef, useState } from "preact/hooks";
import { behaviors } from "./behaviors";
import definitions from "./definitions.json";
import javaCss from "./modes/java.css";
import symbolsCss from "./modes/symbols.css";
import wordsCss from "./modes/words.css";
import program from "./program.json";
import { SIZE_MAX, SIZE_MIN, loadSettings, saveSettings, type Level, type Settings } from "./settings";

// Symbols, Words and Java are modes: they change what a block says. Each
// has a twin with "-help" that also shows the explanation on its tile, and
// definitions.json has a preset for every pair.
const levels: { id: Level; label: string; mode: string; preview: string }[] = [
  { id: "symbols", label: "Symbols", mode: "with-symbols", preview: "plain words" },
  { id: "words", label: "Words", mode: "in-words", preview: "Java" },
  { id: "java", label: "Java", mode: "in-java", preview: "plain words" },
];
const levelOf = (id: Level) => levels.find((level) => level.id === id)!;
const presetName = (settings: Settings) => (settings.help ? `${settings.level}-help` : settings.level);

const modeStyles = {
  "with-symbols": symbolsCss,
  "with-symbols-help": symbolsCss,
  "in-words": wordsCss,
  "in-words-help": wordsCss,
  "in-java": javaCss,
  "in-java-help": javaCss,
};

// The text size changes how things look, not what they say: Blockly's zoom
// for the workspace, CSS for everything else.
const scaleOf = (settings: Settings) => settings.size / 100;

// Code view colors per look; the page's own colors live in style.css.
const codeColors = {
  light: { background: "#fffdf8", foreground: "#111111", gutterBackground: "#f6f1e7", gutterForeground: "#6b6358", selectionBackground: "#efe3ff" },
  dark: { background: "#1d1928", foreground: "#ece7f5", gutterBackground: "#1d1928", gutterForeground: "#a197b5", selectionBackground: "#3d2e5c" },
  lightContrast: { background: "#ffffff", foreground: "#000000", gutterBackground: "#ffffff", gutterForeground: "#000000", selectionBackground: "#ffe066" },
  darkContrast: { background: "#000000", foreground: "#ffffff", gutterBackground: "#000000", gutterForeground: "#ffffff", selectionBackground: "#665200" },
};

function codeTheme(settings: Settings): MorphicCodeEditorTheme {
  const look = settings.dark ? (settings.contrast ? "darkContrast" : "dark") : settings.contrast ? "lightContrast" : "light";
  return {
    ...codeColors[look],
    fontFamily: settings.dyslexia ? '"OpenDyslexic", monospace' : 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
    fontSize: `${Math.round(15 * scaleOf(settings))}px`,
    lineHeight: 1.6,
  };
}

/** Wait for the dyslexia font, so blocks are measured with it, not before. */
const dyslexiaFontReady = () =>
  Promise.all([document.fonts.load('400 16px "OpenDyslexic"'), document.fonts.load('700 16px "OpenDyslexic"')]);

export function App() {
  const [settings, setSettings] = useState(loadSettings);
  const [output, setOutput] = useState<{ lines: string[]; error?: string }>({ lines: [] });
  const [settingsOpen, setSettingsOpen] = useState(false);
  const engine = useRef<MorphicBlocks>();
  // The settings the engine shows right now, to tell what changed.
  const applied = useRef<Settings>();
  const toolboxEl = useRef<HTMLDivElement>(null);
  const workspaceEl = useRef<HTMLDivElement>(null);
  const previewEl = useRef<HTMLDivElement>(null);
  const settingsButton = useRef<HTMLButtonElement>(null);
  const closeButton = useRef<HTMLButtonElement>(null);

  const change = (patch: Partial<Settings>) => setSettings((current) => ({ ...current, ...patch }));

  const run = () => {
    const result = engine.current?.runJavaScript();
    if (!result) return;
    setOutput({ lines: result.output.map((line) => line.text), error: result.error?.message });
  };

  useEffect(() => {
    const created = new MorphicBlocks(definitions, behaviors);
    engine.current = created;
    const mounted = created.mount({
      workspaceContainer: workspaceEl.current!,
      previewContainer: previewEl.current!,
      preset: presetName(settings),
      modeStyles,
      previewTheme: codeTheme(settings),
      // The toolbox is mounted below, so Blockly builds none itself.
      canvasToolbox: true,
      blockly: {
        // Served by the app itself (scripts/copy-blockly-media.mjs), so
        // Blockly never loads images or sounds from Google's server.
        media: "blockly-media/",
        // Zelos has large, rounded blocks that are easy to hit.
        renderer: "zelos",
        trashcan: true,
        zoom: { controls: true, wheel: false, startScale: scaleOf(settings) },
        theme: {
          name: "accessible-blocks",
          base: "classic",
          // The page's CSS paints the workspace, so each look can change it.
          componentStyles: { workspaceBackgroundColour: "transparent", scrollbarColour: "#8a7fa3" },
        },
      },
    });
    // The toolbox is mounted on its own because only this call can leave out
    // the "Mode:" label; mount() always shows it.
    created.mountToolbox(toolboxEl.current!, { modeLabel: false });
    created.loadWorkspace(program);
    created.getWorkspace()?.scroll(0, 0);
    // Show what the starting program prints once everything is set up, so
    // the output matches the blocks on screen.
    void mounted.then(run);
    return () => created.dispose();
  }, []);

  // Every change of level or look goes through here, so the page, the modes
  // and Blockly always agree.
  useEffect(() => {
    saveSettings(settings);
    const root = document.documentElement;
    root.style.fontSize = `${settings.size}%`;
    root.style.setProperty("--tile-zoom", String(scaleOf(settings)));
    root.dataset.bsTheme = settings.dark ? "dark" : "light";
    root.classList.toggle("dark", settings.dark);
    root.classList.toggle("high-contrast", settings.contrast);
    root.classList.toggle("dyslexia", settings.dyslexia);

    let cancelled = false;
    void (async () => {
      if (settings.dyslexia) await dyslexiaFontReady();
      const current = engine.current;
      if (cancelled || !current) return;
      const before = applied.current;
      applied.current = settings;
      // Each level comes as a preset with and without explanations in the
      // toolbox, so one call switches every view.
      const preset = presetName(settings);
      if (current.getActivePreset()?.name !== preset) current.applyPreset(preset);
      // Setting the workspace mode again measures its blocks again, so a new
      // block font takes effect (also on load, when the font was saved as on
      // and arrived after the first measuring).
      if (before ? before.dyslexia !== settings.dyslexia : settings.dyslexia) {
        current.setModes({ workspaceMode: levelOf(settings.level).mode });
      }
      current.getWorkspace()?.setScale(scaleOf(settings));
      current.setPreviewTheme(codeTheme(settings));
    })();
    return () => {
      cancelled = true;
    };
  }, [settings]);

  // The settings panel is a dialog: Escape closes it, and focus moves into it
  // and back to its button.
  useEffect(() => {
    if (!settingsOpen) return;
    closeButton.current?.focus();
    const onKey = (event: KeyboardEvent) => event.key === "Escape" && setSettingsOpen(false);
    addEventListener("keydown", onKey);
    return () => {
      removeEventListener("keydown", onKey);
      settingsButton.current?.focus();
    };
  }, [settingsOpen]);

  const level = levelOf(settings.level);

  return (
    <>
      <a class="skip-link" href="#workspace">
        Skip to your program
      </a>
      <div class="shell" inert={settingsOpen}>
        <header class="app-bar">
          <div class="brand">
            <img src="favicon.svg" alt="" width="36" height="36" />
            <h1>Accessible Blocks</h1>
          </div>
          <div class="btn-group level-switch" role="radiogroup" aria-label="Show blocks as">
            {levels.map((option) => (
              <>
                <input
                  type="radio"
                  class="btn-check"
                  name="level"
                  id={`level-${option.id}`}
                  checked={settings.level === option.id}
                  onChange={() => change({ level: option.id })}
                />
                <label class="btn btn-level" for={`level-${option.id}`}>
                  {option.label}
                </label>
              </>
            ))}
          </div>
          <button
            ref={settingsButton}
            type="button"
            class="btn btn-settings"
            aria-expanded={settingsOpen}
            aria-controls="settings"
            onClick={() => setSettingsOpen(true)}>
            Settings
          </button>
        </header>

        <main class="app-grid">
          <section class="pane toolbox-pane" aria-labelledby="toolbox-title">
            <h2 id="toolbox-title">Blocks</h2>
            <p class="pane-hint">Drag a block into your program.</p>
            <div ref={toolboxEl} class="toolbox" />
          </section>

          <section class="pane workspace-pane" aria-labelledby="workspace-title">
            <h2 id="workspace-title">Your program</h2>
            <div ref={workspaceEl} id="workspace" class="workspace" tabIndex={-1} />
          </section>

          <aside class="side">
            <section class="pane" aria-labelledby="preview-title">
              <h2 id="preview-title">The same program in {level.preview}</h2>
              <div ref={previewEl} class="preview" />
            </section>
            <section class="pane" aria-labelledby="output-title">
              <div class="output-head">
                <h2 id="output-title">Output</h2>
                <button type="button" class="btn btn-run" onClick={run}>
                  Run
                </button>
              </div>
              <pre class="output" aria-live="polite">
                {output.lines.join("\n")}
                {output.error && <span class="output-error">{`\n${output.error}`}</span>}
                {output.lines.length === 0 && !output.error && "The program showed nothing."}
              </pre>
            </section>
          </aside>
        </main>
      </div>

      <div
        id="settings"
        class={`offcanvas offcanvas-end settings${settingsOpen ? " show" : ""}`}
        role="dialog"
        aria-modal="true"
        aria-labelledby="settings-title"
        tabIndex={-1}>
        <div class="offcanvas-header">
          <h2 id="settings-title" class="offcanvas-title">
            Settings
          </h2>
          <button
            ref={closeButton}
            type="button"
            class="btn-close"
            aria-label="Close settings"
            onClick={() => setSettingsOpen(false)}
          />
        </div>
        <div class="offcanvas-body">
          <p class="settings-intro">
            Symbols, Words and Java change what the blocks say. These settings change how everything looks.
          </p>

          <div class="mb-4">
            <label class="form-label size-label" for="setting-size">
              Text size <output for="setting-size">{settings.size}%</output>
            </label>
            <input
              type="range"
              class="form-range"
              id="setting-size"
              min={SIZE_MIN}
              max={SIZE_MAX}
              step={10}
              value={settings.size}
              aria-valuetext={`${settings.size} percent`}
              onInput={(event) => change({ size: Number(event.currentTarget.value) })}
            />
          </div>

          {(
            [
              ["dark", "Dark theme", "Light text on a dark background."],
              ["contrast", "High contrast", "The strongest difference between text and background, with outlined blocks."],
              ["dyslexia", "Font for dyslexia", "OpenDyslexic, with heavier letter bottoms."],
              ["help", "Explain each block", "A short explanation under every block in the toolbox."],
            ] as const
          ).map(([key, label, hint]) => (
            <div class="form-check form-switch setting">
              <input
                class="form-check-input"
                type="checkbox"
                role="switch"
                id={`setting-${key}`}
                aria-describedby={`setting-${key}-hint`}
                checked={settings[key]}
                onChange={(event) => change({ [key]: event.currentTarget.checked })}
              />
              <label class="form-check-label" for={`setting-${key}`}>
                {label}
              </label>
              <div id={`setting-${key}-hint`} class="form-text">
                {hint}
              </div>
            </div>
          ))}

          <p class="settings-note">
            The block colors are chosen so that people with color blindness can tell them apart, and every
            block also says what it does in words, so nothing depends on color alone.
          </p>
        </div>
      </div>
      {settingsOpen && <div class="offcanvas-backdrop fade show" onClick={() => setSettingsOpen(false)} />}
    </>
  );
}
